// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VolleyballApp.API.Data;

namespace VolleyballApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210102211405_PostgresInitial")]
    partial class PostgresInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("VolleyballApp.API.Models.Friendlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int?>("FirstUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirstUserId");

                    b.HasIndex("SecondUserId");

                    b.ToTable("Friendlist");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.Invite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("FriendInvite")
                        .HasColumnType("boolean");

                    b.Property<int?>("InviteFromId")
                        .HasColumnType("integer");

                    b.Property<int?>("InviteToId")
                        .HasColumnType("integer");

                    b.Property<bool>("MatchInvite")
                        .HasColumnType("boolean");

                    b.Property<int?>("MatchInvitedToId")
                        .HasColumnType("integer");

                    b.Property<bool>("RefereeInvite")
                        .HasColumnType("boolean");

                    b.Property<bool>("TeamInvite")
                        .HasColumnType("boolean");

                    b.Property<int?>("TeamInvitedId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamInvitingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InviteFromId");

                    b.HasIndex("InviteToId");

                    b.HasIndex("MatchInvitedToId");

                    b.HasIndex("TeamInvitedId");

                    b.HasIndex("TeamInvitingId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("ClosedSignUp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("TeamLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Adress")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeOfMatch")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int?>("FirstTeamId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRefereeInvited")
                        .HasColumnType("boolean");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int?>("RefereeId")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreId")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirstTeamId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RefereeId");

                    b.HasIndex("ScoreId")
                        .IsUnique();

                    b.HasIndex("SecondTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateRead")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MessageSent")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("RecipientDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RecipientId")
                        .HasColumnType("integer");

                    b.Property<bool>("SenderDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("PublicId")
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("FirstTeamSets")
                        .HasColumnType("integer");

                    b.Property<int>("FiveFirstTeam")
                        .HasColumnType("integer");

                    b.Property<int>("FiveSecondTeam")
                        .HasColumnType("integer");

                    b.Property<int>("FourFirstTeam")
                        .HasColumnType("integer");

                    b.Property<int>("FourSecondTeam")
                        .HasColumnType("integer");

                    b.Property<int>("OneFirstTeam")
                        .HasColumnType("integer");

                    b.Property<int>("OneSecondTeam")
                        .HasColumnType("integer");

                    b.Property<int>("SecondTeamSets")
                        .HasColumnType("integer");

                    b.Property<int>("ThreeFirstTeam")
                        .HasColumnType("integer");

                    b.Property<int>("ThreeSecondTeam")
                        .HasColumnType("integer");

                    b.Property<int>("TwoFirstTeam")
                        .HasColumnType("integer");

                    b.Property<int>("TwoSecondTeam")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("RankingPoints")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.TeamLeague", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("LeagueGames")
                        .HasColumnType("integer");

                    b.Property<int>("LeagueLosses")
                        .HasColumnType("integer");

                    b.Property<int>("LeagueScore")
                        .HasColumnType("integer");

                    b.Property<int>("LeagueWins")
                        .HasColumnType("integer");

                    b.HasKey("LeagueId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamLeague");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("GamesWon")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("IsMailActivated")
                        .HasColumnType("boolean");

                    b.Property<string>("KnownAs")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Mail")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("Positions")
                        .HasColumnType("text");

                    b.Property<int>("RankingPoints")
                        .HasColumnType("integer");

                    b.Property<string>("UserType")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.UserTeam", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsTeamOwner")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserTeam");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.Friendlist", b =>
                {
                    b.HasOne("VolleyballApp.API.Models.User", "FirstUser")
                        .WithMany()
                        .HasForeignKey("FirstUserId");

                    b.HasOne("VolleyballApp.API.Models.User", "SecondUser")
                        .WithMany()
                        .HasForeignKey("SecondUserId");

                    b.Navigation("FirstUser");

                    b.Navigation("SecondUser");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.Invite", b =>
                {
                    b.HasOne("VolleyballApp.API.Models.User", "InviteFrom")
                        .WithMany()
                        .HasForeignKey("InviteFromId");

                    b.HasOne("VolleyballApp.API.Models.User", "InviteTo")
                        .WithMany()
                        .HasForeignKey("InviteToId");

                    b.HasOne("VolleyballApp.API.Models.Match", "MatchInvitedTo")
                        .WithMany()
                        .HasForeignKey("MatchInvitedToId");

                    b.HasOne("VolleyballApp.API.Models.Team", "TeamInvited")
                        .WithMany()
                        .HasForeignKey("TeamInvitedId");

                    b.HasOne("VolleyballApp.API.Models.Team", "TeamInviting")
                        .WithMany()
                        .HasForeignKey("TeamInvitingId");

                    b.Navigation("InviteFrom");

                    b.Navigation("InviteTo");

                    b.Navigation("MatchInvitedTo");

                    b.Navigation("TeamInvited");

                    b.Navigation("TeamInviting");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.League", b =>
                {
                    b.HasOne("VolleyballApp.API.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.Match", b =>
                {
                    b.HasOne("VolleyballApp.API.Models.Team", "FirstTeam")
                        .WithMany()
                        .HasForeignKey("FirstTeamId");

                    b.HasOne("VolleyballApp.API.Models.League", "League")
                        .WithMany("Matches")
                        .HasForeignKey("LeagueId");

                    b.HasOne("VolleyballApp.API.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("VolleyballApp.API.Models.User", "Referee")
                        .WithMany("RefereeMatches")
                        .HasForeignKey("RefereeId");

                    b.HasOne("VolleyballApp.API.Models.Score", "Score")
                        .WithOne("Match")
                        .HasForeignKey("VolleyballApp.API.Models.Match", "ScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyballApp.API.Models.Team", "SecondTeam")
                        .WithMany()
                        .HasForeignKey("SecondTeamId");

                    b.Navigation("FirstTeam");

                    b.Navigation("League");

                    b.Navigation("Location");

                    b.Navigation("Referee");

                    b.Navigation("Score");

                    b.Navigation("SecondTeam");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.Message", b =>
                {
                    b.HasOne("VolleyballApp.API.Models.User", "Recipient")
                        .WithMany("MessagesReceived")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballApp.API.Models.User", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.Photo", b =>
                {
                    b.HasOne("VolleyballApp.API.Models.Team", "Team")
                        .WithOne("Photo")
                        .HasForeignKey("VolleyballApp.API.Models.Photo", "TeamId");

                    b.HasOne("VolleyballApp.API.Models.User", "User")
                        .WithOne("Photo")
                        .HasForeignKey("VolleyballApp.API.Models.Photo", "UserId");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.Team", b =>
                {
                    b.HasOne("VolleyballApp.API.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.TeamLeague", b =>
                {
                    b.HasOne("VolleyballApp.API.Models.League", "League")
                        .WithMany("TeamLeague")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyballApp.API.Models.Team", "Team")
                        .WithMany("TeamLeague")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.UserTeam", b =>
                {
                    b.HasOne("VolleyballApp.API.Models.Team", "Team")
                        .WithMany("UserTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyballApp.API.Models.User", "User")
                        .WithOne("UserTeam")
                        .HasForeignKey("VolleyballApp.API.Models.UserTeam", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.League", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("TeamLeague");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.Score", b =>
                {
                    b.Navigation("Match");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.Team", b =>
                {
                    b.Navigation("Photo");

                    b.Navigation("TeamLeague");

                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("VolleyballApp.API.Models.User", b =>
                {
                    b.Navigation("MessagesReceived");

                    b.Navigation("MessagesSent");

                    b.Navigation("Photo");

                    b.Navigation("RefereeMatches");

                    b.Navigation("UserTeam");
                });
#pragma warning restore 612, 618
        }
    }
}
